listen_addresses = '*'
port = 5432

# TLS (in-transit encryption)
ssl = on
ssl_cert_file = '/var/lib/postgresql/server.crt'
ssl_key_file = '/var/lib/postgresql/server.key'

# Reasonable defaults
password_encryption = scram-sha-256

